name: genefab
channels:
  - defaults
dependencies:
  - blas
  - ca-certificates
  - certifi
  - icc_rt
  - intel-openmp
  - mkl
  - mkl_fft
  - mkl_random
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pip
  - python=3.7.2
  - python-dateutil
  - pytz
  - setuptools
  - six
  - sqlite
  - wheel
